FROM ghcr.io/durantic/durantic-userspace-ubuntu:30dd16304aafb54fe6e90d475f23e37052de906a

# Add SSH key for ubuntu user
RUN mkdir -p /home/ubuntu/.ssh && \
    echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDXx2yoM90ZD4d54VnU1CdpOV73AHyI+RpIoNSlBCYMaYcEo1k0IByJ8/Vwg0jgug1j4xb++LF512D4ZkzaXp/eGtHssOHMp/d6Ossm2KgMesal7V08zdUa37HHnn3A0pHMojdQFCefxYiQF+wO4fEEKvSD3mPGKDnaLbl35M2qZ4daVdsmk8K0QX7aSHTxkxIkkPLsWYDZs/FwLziWRTFSdSkd18o/OHnEEvjVyAiPCjut6Il8Fyar8xR6Oi8zsWor24L515WJTT/ABtZ+Su9cAek8b4vFBhYw+yiAi2O6n98UNi+kWOhPIwMUGDopa4GgTo6WOCutDdL+/VxfPF7F" > /home/ubuntu/.ssh/authorized_keys && \
    chown -R ubuntu:ubuntu /home/ubuntu/.ssh && \
    chmod 700 /home/ubuntu/.ssh && \
    chmod 600 /home/ubuntu/.ssh/authorized_keys

